plugins {
    id 'com.android.application'
}

android {
    namespace 'com.t3r0za.panel'
    compileSdk 36

    defaultConfig {
        applicationId 'com.t3r0za.panel'
        minSdk 26
        targetSdk 36
        versionCode 3
        versionName '3.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
