plugins {
    id 'com.android.application'
}

android {
    namespace 'com.t3r0za.mobile'
    compileSdk 36

    defaultConfig {
        applicationId 'com.t3r0za.mobile'
        minSdk 26
        targetSdk 36
        versionCode 2
        versionName '1.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}